In [65]:
import numpy as np
import pandas as pd

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
df = pd.read_csv("C:/Users/Vidush/Desktop/Dataset/smsspamcollection.tsv", sep='\t')

In [68]:
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [69]:
df = df.drop(['length', 'punct'], axis=1)

In [70]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [71]:
#Finding out how many spam and ham
print("Total Spam is ", len(df[df.label=='spam']))
print("Total Ham is ", len(df[df.label=='ham']))

Total Spam is  747
Total Ham is  4825


In [72]:
#Changing ham into 1 & spam into 0
df.loc[df['label']=='ham', 'label'] = 1
df.loc[df['label']=='spam', 'label'] = 0

In [73]:
df.head()

label                                            message
0     1  Go until jurong point, crazy.. Available only ...
1     1                      Ok lar... Joking wif u oni...
2     0  Free entry in 2 a wkly comp to win FA Cup fina...
3     1  U dun say so early hor... U c already then say...
4     1  Nah I don't think he goes to usf, he lives aro...

In [74]:
df_x = df["message"]
df_y = df["label"]

In [75]:
df_x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [76]:
cv = TfidfVectorizer(min_df=1, stop_words = 'english')

In [77]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.33, random_state=42)

In [78]:
x_traincv = cv.fit_transform(x_train)

In [79]:
a = x_traincv.toarray()

In [80]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [81]:
a[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [82]:
cv.inverse_transform(a[0])

[array(['comin', 'yup'], dtype='<U34')]

In [83]:
x_train.iloc[0]

'Yup ü not comin :-('

In [84]:
mnb = MultinomialNB()

In [85]:
y_train = y_train.astype('int')

In [86]:
mnb.fit(x_traincv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [87]:
x_testcv = cv.transform(x_test)

In [89]:
pred = mnb.predict(x_testcv)

In [90]:
pred

array([1, 1, 1, ..., 1, 1, 1])

In [93]:
actual = np.array(y_test)

In [94]:
actual

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

In [95]:
count = 0
for i in range(len(pred)):
    if pred[i] == actual[i]:
        count = count + 1

In [96]:
count

1784

In [97]:
len(pred)

1839

In [98]:
1784/1839

0.9700924415443176